channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - protobuf=3.13.0
  - numpy=1.19.5
  - pip=20.3.3
  - scikit-learn=0.24.1
  - mlflow=1.14.1
  - pip=20.3.3
  - pip:
      - cloudpickle==2.2.1
name: mlflow-env
