name: udacity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - protobuf=3.13.0
  - jupyterlab=3.0.12
  - numpy=1.19.5
  - pandas=1.2.3
  - requests=2.24.0
  - pip=20.3.3
  - matplotlib==3.2.2
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.21
      - notebook==6.1.0
