name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - protobuf=3.13.0
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - jinja2=2.11.2
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.10.21